---
title: "Portfolio_3"
author: "Ben Hardin"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-data-packages}
library(tidyverse)
library(jsonlite)
```

```{r load-data}
spotify <- "StreamingHistory0.JSON" %>%
  fromJSON() %>%
  as_tibble() %>%
  glimpse()
```

```{r music}
spotify %>%
  count(artistName) %>%
  arrange(desc(n))

spotify <- spotify %>%
  filter(!artistName %in% c("Very Bad Wizards", "Unknown Artist", "Decoding the Gurus", "Taskmaster The Podcast", "Two Psychologists Four Beers", "Better Call Saul Insider Podcast", "Off Menu with Ed Gamble and James Acaster"))

spotify <- spotify %>%
  group_by(artistName) %>%
  mutate(plays = n())
```

```{r getting-top-artists}
spotify_top <-  spotify %>%
  filter(plays >= 40)

spotify_top %>%
  count(artistName) %>%
  arrange(desc(n))
```

```{r first-plot}
ggplot(spotify_top, aes(y = artistName, x = endTime, color = artistName))+
  geom_point(position = "jitter")+
  theme(axis.text.y = element_blank())
```

```{r date-package}
library(lubridate)
```

```{r reshaping}
spotify_top$month <- month(ymd_hm(spotify_top$endTime))

spotify_top <- spotify_top %>%
  group_by(month, artistName) %>%
  mutate(monthly_plays = n())

spotify_monthly <- aggregate(monthly_plays ~ month + artistName, data = spotify_top, FUN = mean)
```

```{r better-plot}
ggplot(spotify_monthly, aes(x = month, y = monthly_plays, color = artistName))+
  geom_line()
```

```{r being-selective}
spotify_top8 <-  spotify_top %>%
  filter(plays > 80)

spotify_monthly <- aggregate(monthly_plays ~ month + artistName + plays, data = spotify_top8, FUN = mean)
```

```{r base-plot}
ggplot(spotify_monthly, aes(x = month, y = monthly_plays, color = fct_reorder(artistName, plays, .desc = TRUE)))+
  geom_line(linewidth = 1.3)
```

### Make it better

```{r improve-plot, fig.width = 10}
spotify_monthly <- spotify_monthly %>%
  mutate(month_name = month.name[spotify_monthly$month])

ggplot(spotify_monthly, aes(x = fct_reorder(month_name, month), y = monthly_plays, group = fct_reorder(artistName, plays, .desc = TRUE), color = fct_reorder(artistName, plays)))+
  geom_line(lineend = "round", aes(linewidth = fct_reorder(artistName, plays)))+
  scale_color_viridis_d()+
  theme_bw()+
  labs(title = "Listening Trends for Ben's top artists (2022)",
       x = "Month",
       y = "Plays",
       color = "Artist",
       linewidth = "Artist")
```

```{r even-better, fig.width = 10}
spotify_monthly <- spotify_monthly %>%
  mutate(month_name = month.name[spotify_monthly$month])

ggplot(spotify_monthly, aes(x = fct_reorder(month_name, month), y = monthly_plays, group = fct_reorder(artistName, plays, .desc = TRUE), color = fct_reorder(artistName, plays)))+
  geom_line(lineend = "round", 
            aes(linewidth = fct_reorder(artistName, plays)))+
  guides(color = guide_legend(reverse = TRUE), linewidth = guide_legend(reverse = TRUE))+
  scale_color_viridis_d(option = "F", direction = 1)+
  theme_classic()+
  theme(
    legend.position = c(.95, .95),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6))+
  labs(title = "Listening Trends for Ben's top artists (2022)",
       x = "Month",
       y = "Plays",
       color = "Ben's top artists",
       linewidth = "Ben's top artists")
```

### Mapping the geography of my music

```{r starting-somewhere}
artist_plays <- spotify %>%
  count(artistName) %>%
  filter(n > 11) %>%
  filter(!artistName %in% c("You're Wrong About", "My Brother, My Brother And Me"))
```

[after all the making functions and writing scripts we just did]

```{r joining-data}
artist_towns <- read.csv("data/artist_towns.csv")
origin_coords <- read.csv("data/origin_coords.csv")

artist_map <- inner_join(artist_plays, artist_towns, by = "artistName")

artist_map <- inner_join(artist_map, origin_coords, by = "origin") %>%
  filter(!is.na(long))
```

```{r coordinates-function, include=FALSE}
dms2dec <- function(dms, separators = c("º", "°", "\'", "′", "’’", "″", "\'\'", "\\?")) {
  
  # version 1.4 (2 Feb 2022)
  # dms: a vector of latitude or longitude in degrees-minutes-seconds-hemisfere, e.g. 41° 34' 10.956" N (with or without spaces)
  # separators: the characters that are separating degrees, minutes and seconds in 'dms'; mind these are taken in the order in which they appear and not interpreted individually, i.e. 7'3º will be taken as 7 degrees, 3 minutes! input data are assumed to be properly formatted
  
  dms <- as.character(dms)
  dms <- gsub(pattern = " ", replacement = "", x = dms)
  for (s in separators) dms <- gsub(pattern = s, replacement = "_splitHere_", x = dms)
  
  splits <- strsplit(dms, split = "_splitHere_")
  n <- length(dms)
  deg <- min <- sec <- hem <- vector("character", n)
  
  for (i in 1:n) {
    deg[i] <- splits[[i]][1]
    min[i] <- splits[[i]][2]
    
    if (length(splits[[i]]) < 4) {
      hem[i] <- splits[[i]][3]
    } else {
      sec[i] <- splits[[i]][3]
      hem[i] <- splits[[i]][4]
    }
  }
  
  dec <- colSums(rbind(as.numeric(deg), (as.numeric(min) / 60), (as.numeric(sec) / 3600)), na.rm = TRUE)
  sign <- ifelse (hem %in% c("N", "E"), 1, -1)
  hem_miss <- which(is.na(hem))
  if (length(hem_miss) > 0) {
    warning("Hemisphere not specified at position(s) ", hem_miss, ", so the sign of the resulting coordinates may be wrong.")
  }
  dec <- sign * dec
  return(dec)
}  # end dms2dec function

```

```{r cleaning-coords}
artist_map$long.dec <- dms2dec(artist_map$long)

artist_map$lat.dec <- dms2dec(artist_map$lat)

#credit:https://www.r-bloggers.com/2022/02/degree-minute-second-to-decimal-coordinates/
```

```{r try-map}
library(maps)

world <- map_data("world")

ggplot(artist_map, aes(x = long.dec, y = lat.dec))+
  geom_point()+
  geom_polygon(data = world, aes(x = long, y = lat))
```

```{r try-again}
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "grey90")+
  geom_point(data = artist_map, aes(x = long.dec, y = (lat.dec), size = n, label = artistName), color = "skyblue3", alpha = .7)+
  theme_void()+
  theme(legend.position = "none")
```

```{r interactive}
library(plotly)

music_map <- 
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "grey90")+
  geom_point(data = artist_map, aes(x = long.dec, y = (lat.dec), size = n, label = artistName), color = "skyblue3", alpha = .7)+
  theme_void()+
  theme(legend.position = "none")

ggplotly(music_map, tooltip = "label")
```